export const fallbackExtraItemsCatalog = [
  { code: "EX001", name: "Aaloo Patties (1 Pc.)", price: 15, priceLabel: "15" },
  { code: "EX002", name: "Ice Cream", price: 15, priceLabel: "15" },
  { code: "EX003", name: "Kheer / Sewiyan", price: 20, priceLabel: "To be decided every week" },
  { code: "EX004", name: "Gulabjamun", price: 15, priceLabel: "15" },
  { code: "EX005", name: "Paneer Kulcha", price: 15, priceLabel: "15" },
  { code: "EX006", name: "Chana Samosa (2 Pc.)", price: 28, priceLabel: "28" },
  { code: "EX007", name: "Chana Samosa (1 Pc.)", price: 35, priceLabel: "35" },
  { code: "EX008", name: "Spring Roll (1 Pc.)", price: 20, priceLabel: "20" },
  { code: "EX009", name: "Milk Glass", price: 15, priceLabel: "15" },
  { code: "EX010", name: "Milk Half Glass", price: 26, priceLabel: "26" },
  { code: "EX011", name: "Boiled Egg (1 Pc.)", price: 14, priceLabel: "14" },
  { code: "EX012", name: "Sponge Rasgulla", price: 8, priceLabel: "8" },
  { code: "EX013", name: "Pastry", price: 14, priceLabel: "14" },
  { code: "EX014", name: "Omelette / Egg Bhurji", price: 21, priceLabel: "21" },
  { code: "EX015", name: "Butter (1 Pc.)", price: 22, priceLabel: "22" },
  { code: "EX016", name: "Noodles / Maggi", price: 10, priceLabel: "10" },
  { code: "EX017", name: "Paneer Extra", price: 20, priceLabel: "20" },
  { code: "EX018", name: "Chicken Extra", price: 20, priceLabel: "20" },
  { code: "EX019", name: "Dosa / Uttapam Extra", price: 80, priceLabel: "80" },
  { code: "EX020", name: "Naan Extra", price: 34, priceLabel: "34" },
  { code: "EX021", name: "Bread (1 Pc.)", price: 3, priceLabel: "3" },
  { code: "EX022", name: "Cornflakes Extra", price: 15, priceLabel: "15" },
  { code: "EX023", name: "Fruit Chart", price: 30, priceLabel: "30" },
  { code: "EX024", name: "Cutlet (2 Pc.)", price: 20, priceLabel: "20" },
  { code: "EX025", name: "Cutlet (1 Pc.)", price: 12, priceLabel: "12" },
  { code: "EX026", name: "Bread Pakoda (2 Pc.)", price: 25, priceLabel: "25" },
  { code: "EX027", name: "Bread Pakoda (1 Pc.)", price: 15, priceLabel: "15" },
  { code: "EX028", name: "Banana", price: 10, priceLabel: "To be decided every week" },
  { code: "EX029", name: "Malai Jam", price: 14, priceLabel: "14" },
  { code: "EX030", name: "Rasmalai", price: 33, priceLabel: "33" },
  { code: "EX031", name: "Bread Roll (2 Pc.)", price: 25, priceLabel: "25" },
  { code: "EX032", name: "Peanut Butter (Small Spoon)", price: 5, priceLabel: "5 per spoon (Small)" },
  { code: "EX033", name: "Moong Halwa", price: 25, priceLabel: "25" },
  { code: "EX034", name: "Pav (Small)", price: 5, priceLabel: "5" },
  { code: "EX035", name: "Pav (Big)", price: 10, priceLabel: "10" },
  { code: "EX036", name: "Nariyal Burfi", price: 10, priceLabel: "10" },
  { code: "EX037", name: "Idli / Vada", price: 12, priceLabel: "12 per pcs." },
  { code: "EX038", name: "Milk Cake", price: 16, priceLabel: "16" },
  { code: "EX039", name: "Hot Dog", price: 15, priceLabel: "15" },
  { code: "EX040", name: "Rabadi / Jalebi", price: 22, priceLabel: "22" },
  { code: "EX041", name: "Manchurian", price: 25, priceLabel: "25" },
  { code: "EX042", name: "Desi Ghee Pinni", price: 23, priceLabel: "23" },
  { code: "EX043", name: "Kachori", price: 20, priceLabel: "20" },
  { code: "EX044", name: "Allo Tikki", price: 30, priceLabel: "30" },
  { code: "EX045", name: "Extra Meal", price: 55, priceLabel: "55" },
  { code: "EX046", name: "Chips", price: 20, priceLabel: "20" },
  { code: "EX047", name: "Biscuit", price: 10, priceLabel: "10" },
];
